# Copyright (c) Forward Email LLC
# SPDX-License-Identifier: BUSL-1.1

---
- hosts: imap:pop3:smtp:http:bree:sqlite:mx1:mx2:mail
  name: Google Application Credentials
  vars_prompt:
    - name: input_profile
      prompt: Enter path to Google application credentials profile file (used for translation with `mandarin`) (e.g. /path/to/client-profile.json)
      private: false

  tasks:
    # profile file
    - name: Check if profile file exists
      local_action: stat path={{ input_profile }}
      become: false
      register: local_profile_file
    - name: Fail when local profile file does not exist
      fail:
        msg: "profile file does not exist: {{ input_profile }}"
      when: not local_profile_file.stat.exists

    # remote dir
    - name: Check if remote dir exists
      stat:
        path: /var/www/production
      register: remote_dir

    - name: Fail when remote dir does not exist
      fail:
        msg: pm2 dir not yet created
      when: not remote_dir.stat.exists or not remote_dir.stat.isdir

    # copy local profile
    - name: Copy local profile file to server
      copy:
        src: "{{ input_profile }}"
        dest: /var/www/production/.gapp-creds.json
        owner: deploy
        # https://chmodcommand.com/chmod-660/
        mode: "0660"
