# Copyright (c) Forward Email LLC
# SPDX-License-Identifier: BUSL-1.1

---
- name: Import security playbook
  import_playbook: security.yml
- name: Import Node.js playbook
  import_playbook: node.yml
- name: Import SSH keys playbook
  import_playbook: ssh-keys.yml
- hosts: web
  name: Web Hostname
  become: true
  become_user: root
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ lookup('env', 'WEB_HOST') }}"
- hosts: api
  name: API Hostname
  become: true
  become_user: root
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ lookup('env', 'API_HOST') }}"
- hosts: caldav
  name: CalDAV Hostname
  become: true
  become_user: root
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ lookup('env', 'CALDAV_HOST') }}"
- hosts: carddav
  name: CardDAV Hostname
  become: true
  become_user: root
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ lookup('env', 'CARDDAV_HOST') }}"
- hosts: web:api:caldav:carddav
  name: HTTP
  become: true
  become_user: root
  # this was already defined in the ufw role
  # https://github.com/Oefenweb/ansible-ufw/blob/master/handlers/main.yml
  handlers:
    - name: Reload UFW
      ufw:
        state: reloaded
  tasks:
    # ufw
    - name: Enable ufw
      ufw:
        state: enabled
        policy: deny
        direction: incoming
    - name: Limit ufw ssh
      ufw:
        rule: limit
        port: 22
        proto: tcp
    - name: Allow ssh
      ufw:
        rule: allow
        port: 22
        proto: tcp
    - name: Allow http
      ufw:
        rule: allow
        port: "{{ lookup('env', 'PROXY_PORT') }}"
        proto: tcp
    - name: Allow https
      ufw:
        rule: allow
        port: "{{ lookup('env', 'HTTP_PORT') }}"
        proto: tcp
    #
    # modify ufw setup
    # https://github.com/Oefenweb/ansible-ufw/issues/21
    #
    - name: "Update ufw before.rules until #21 is resolved"
      template:
        src: "{{ playbook_dir }}/templates/before.rules.j2"
        dest: /etc/ufw/before.rules
        owner: root
        mode: "0644"
      notify: Reload UFW
