# Copyright (c) Forward Email LLC
# SPDX-License-Identifier: BUSL-1.1

---
- name: Import security playbook
  import_playbook: security.yml
- name: Import Node.js playbook
  import_playbook: node.yml
- name: Import SSH keys playbook
  import_playbook: ssh-keys.yml
- hosts: smtp
  name: Hostname
  become: true
  become_user: root
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ lookup('env', 'SMTP_HOST') }}"

- hosts: smtp
  name: SMTP
  become: true
  become_user: root
  # this was already defined in the ufw role
  # https://github.com/Oefenweb/ansible-ufw/blob/master/handlers/main.yml
  handlers:
    - name: Reload UFW
      ufw:
        state: reloaded
  tasks:
    # ufw
    - name: Enable ufw
      ufw:
        state: enabled
        policy: deny
        direction: incoming
    - name: Limit ufw ssh
      ufw:
        rule: limit
        port: 22
        proto: tcp
    - name: Set UFW default forward policy to DROP
      lineinfile:
        dest: /etc/default/ufw
        line: DEFAULT_FORWARD_POLICY="DROP"
        regexp: ^DEFAULT_FORWARD_POLICY\=
    - name: Allow ssh
      ufw:
        rule: allow
        port: 22
        proto: tcp
    - name: Allow port 25
      ufw:
        rule: allow
        port: 25
        proto: tcp
    - name: Allow port 587
      ufw:
        rule: allow
        port: 587
        proto: tcp
    - name: Allow port 2525
      ufw:
        rule: allow
        port: 2525
        proto: tcp
    - name: Allow port 2587
      ufw:
        rule: allow
        port: 2587
        proto: tcp
    - name: Allow port 465
      ufw:
        rule: allow
        port: 465
        proto: tcp
    - name: Allow port 2465
      ufw:
        rule: allow
        port: 2465
        proto: tcp
    # tls 1.0 with SSL
    - name: Allow port 2455
      ufw:
        rule: allow
        port: 2455
        proto: tcp
    # tls 1.0 with STARTTLS
    - name: Allow port 2555
      ufw:
        rule: allow
        port: 2555
        proto: tcp
    - name: Allow http
      ufw:
        rule: allow
        port: "{{ lookup('env', 'PROXY_PORT') }}"
        proto: tcp
    - name: Allow https
      ufw:
        rule: allow
        port: "{{ lookup('env', 'HTTP_PORT') }}"
        proto: tcp
    #
    # modify ufw setup
    # https://github.com/Oefenweb/ansible-ufw/issues/21
    #
    - name: "Update ufw before.rules until #21 is resolved"
      template:
        src: "{{ playbook_dir }}/templates/before.rules.j2"
        dest: /etc/ufw/before.rules
        owner: root
        mode: "0644"
      notify: Reload UFW
